# Generated by Django 2.2.1 on 2019-05-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retangulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado_a', models.IntegerField()),
                ('lado_b', models.IntegerField()),
            ],
        ),
    ]
